"""add_ssid_and_contact_to_tenant_settings

Revision ID: 3857e2251aa1
Revises: e60378fd8260
Create Date: 2026-04-18 02:05:46.199887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3857e2251aa1'
down_revision = 'e60378fd8260'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
