"""Remove incorrect node->plans relationship

Revision ID: 7069c25b42eb
Revises: 0643195d1bb7
Create Date: 2026-04-07 22:01:19.484508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7069c25b42eb'
down_revision = '0643195d1bb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
