"""add free subscription fields to tenant

Revision ID: 744fa42cca13
Revises: fix_tenant_roles_001
Create Date: 2026-04-27 11:43:53.780084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744fa42cca13'
down_revision = 'fix_tenant_roles_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('free_subscription_until', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('free_subscription_plan', sa.String(50), nullable=True))
    op.add_column('tenants', sa.Column('free_subscription_reason', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'free_subscription_reason')
    op.drop_column('tenants', 'free_subscription_plan')
    op.drop_column('tenants', 'free_subscription_until')
    # ### end Alembic commands ###
