"""fix_upgrade_requests_table

Revision ID: 8f8548709ef9
Revises: 03da7e1a34f5
Create Date: 2026-04-27 02:09:21.246811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8548709ef9'
down_revision = '03da7e1a34f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_exchange_rates_active', table_name='exchange_rates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_exchange_rates_active', 'exchange_rates', ['is_active', 'created_at'], unique=False)
    # ### end Alembic commands ###
