"""Create pricing_plans table for SaaS plans

Revision ID: a7c2f8d9e4b1
Revises: 8f8548709ef9
Create Date: 2026-04-30 05:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a7c2f8d9e4b1'
down_revision = '8f8548709ef9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pricing_plans',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tier', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('included_tickets_per_month', sa.Integer(), nullable=False),
        sa.Column('additional_ticket_pack_size', sa.Integer(), nullable=False, server_default='100'),
        sa.Column('additional_ticket_pack_price', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('is_tickets_unlimited', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('included_nodes', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('additional_node_price', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('is_nodes_unlimited', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('has_api_access', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('api_access_level', sa.String(length=50), nullable=False, server_default='none'),
        sa.Column('support_level', sa.String(length=50), nullable=False),
        sa.Column('reports_level', sa.String(length=50), nullable=False, server_default='basic'),
        sa.Column('data_retention_days', sa.Integer(), nullable=False, server_default='30'),
        sa.Column('icon', sa.String(length=50), nullable=False, server_default='wifi'),
        sa.Column('color', sa.String(length=50), nullable=False, server_default='blue'),
        sa.Column('is_recommended', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tier')
    )
    op.create_index('ix_pricing_plans_tier', 'pricing_plans', ['tier'])
    op.create_index('ix_pricing_plans_is_active', 'pricing_plans', ['is_active'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pricing_plans_is_active')
    op.drop_index('ix_pricing_plans_tier')
    op.drop_table('pricing_plans')
    # ### end Alembic commands ###
