"""Add PricingConfig model for global pricing configuration

Revision ID: f8b3c4d5e6f7
Revises: f7a2b9c3d4e5
Create Date: 2026-04-26 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f8b3c4d5e6f7'
down_revision = 'f7a2b9c3d4e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pricing_configs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('ticket_pack_size', sa.Integer(), nullable=False, server_default='50'),
        sa.Column('ticket_pack_price_usd', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.50'),
        sa.Column('additional_node_price_usd', sa.Numeric(precision=10, scale=2), nullable=False, server_default='50.00'),
        sa.Column('free_plan_max_nodes', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('free_plan_max_tickets', sa.Integer(), nullable=False, server_default='50'),
        sa.Column('basic_plan_max_nodes', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('basic_plan_max_free_tickets', sa.Integer(), nullable=False, server_default='50'),
        sa.Column('description', sa.String(length=500), nullable=False, server_default='Default pricing configuration'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_configs')
    # ### end Alembic commands ###
