"""Add ticket tracking fields to Tenant model

Revision ID: f7a2b9c3d4e5
Revises: 3857e2251aa1
Create Date: 2026-04-26 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a2b9c3d4e5'
down_revision = '3857e2251aa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('free_tickets_used', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tenants', sa.Column('free_tickets_limit', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('tenants', sa.Column('extra_tickets_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'extra_tickets_count')
    op.drop_column('tenants', 'free_tickets_limit')
    op.drop_column('tenants', 'free_tickets_used')
    # ### end Alembic commands ###
