'''Add subscription fields to Tenant model

Revision ID: b78a67490fa6
Revises: 7069c25b42eb
Create Date: 2026-04-10 11:51:33.438892

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78a67490fa6'
down_revision = '7069c25b42eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_status_enum = sa.Enum('trialing', 'active', 'past_due', 'canceled', 'unpaid', name='subscriptionstatus')
    subscription_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'tenants',
        sa.Column(
            'subscription_status',
            subscription_status_enum,
            server_default='trialing',
            nullable=False
        )
    )
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_tenant_stripe_customer_id', 'tenants', ['stripe_customer_id'])
    # ### end Alembic commands ###

    # ### Manually added indexes ###
    op.create_index('idx_ticket_node_status', 'tickets', ['node_id', 'status'], unique=False)
    op.create_index('idx_session_active', 'sessions', ['node_id', 'is_active', 'expires_at'], unique=False)
    op.create_index('idx_node_tenant', 'nodes', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_tenant_slug', 'tenants', ['slug'], unique=False)
    # ### end Manually added indexes ###


def downgrade() -> None:
    # ### Manually added indexes ###
    op.drop_index('idx_tenant_slug', table_name='tenants')
    op.drop_index('idx_node_tenant', table_name='nodes')
    op.drop_index('idx_session_active', table_name='sessions')
    op.drop_index('idx_ticket_node_status', table_name='tickets')
    # ### end Manually added indexes ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_stripe_customer_id', 'tenants', type_='unique')
    op.drop_column('tenants', 'stripe_customer_id')
    op.drop_column('tenants', 'subscription_status')
    # ### end Alembic commands ###

