"""add_full_name_and_tenant_role_to_user

Revision ID: e160bea57250
Revises: 8f8548709ef9
Create Date: 2026-04-27 11:27:14.886518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e160bea57250'
down_revision = '8f8548709ef9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create the enum type first for PostgreSQL
    op.execute("CREATE TYPE tenantrole AS ENUM ('owner', 'admin', 'collaborator', 'viewer')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('tenant_role', sa.Enum('owner', 'admin', 'collaborator', 'viewer', name='tenantrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tenant_role')
    op.drop_column('users', 'full_name')
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS tenantrole")
    # ### end Alembic commands ###
