"""Add deleted_at field for soft deletes

Revision ID: e60378fd8260
Revises: b78a67490fa6
Create Date: 2026-04-18 01:42:02.223028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60378fd8260'
down_revision = 'b78a67490fa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_metrics', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('nodes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('idx_node_tenant', table_name='nodes')
    op.add_column('plans', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('idx_session_active', table_name='sessions')
    op.add_column('tenants', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('idx_tenant_slug', table_name='tenants')
    op.add_column('tickets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('idx_ticket_node_status', table_name='tickets')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.create_index('idx_ticket_node_status', 'tickets', ['node_id', 'status'], unique=False)
    op.drop_column('tickets', 'deleted_at')
    op.create_index('idx_tenant_slug', 'tenants', ['slug'], unique=False)
    op.drop_column('tenants', 'deleted_at')
    op.create_index('idx_session_active', 'sessions', ['node_id', 'is_active', 'expires_at'], unique=False)
    op.drop_column('sessions', 'deleted_at')
    op.drop_column('plans', 'deleted_at')
    op.create_index('idx_node_tenant', 'nodes', ['tenant_id', 'status'], unique=False)
    op.drop_column('nodes', 'deleted_at')
    op.drop_column('node_metrics', 'deleted_at')
    # ### end Alembic commands ###
