"""Add deleted_at to pricing_configs

Revision ID: e8207eb00a46
Revises: f8b3c4d5e6f7
Create Date: 2026-04-26 15:53:30.753562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8207eb00a46'
down_revision = 'f8b3c4d5e6f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_configs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_configs', 'deleted_at')
    # ### end Alembic commands ###
