"""Add wan_ip column to nodes

Revision ID: eb6f7ed4e560
Revises: f9c8e5d4c3b2
Create Date: 2026-04-26 18:28:11.180648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb6f7ed4e560'
down_revision = 'f9c8e5d4c3b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upgrade_requests')
    op.add_column('nodes', sa.Column('wan_ip', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'wan_ip')
    op.create_table('upgrade_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('upgrade_type', postgresql.ENUM('extra_tickets', 'plan_upgrade', name='upgradetype'), autoincrement=False, nullable=False),
    sa.Column('ticket_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_plan_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_method', postgresql.ENUM('cash', 'mobile_pay', 'gateway', name='paymentmethod'), autoincrement=False, nullable=False),
    sa.Column('amount_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount_vef', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('exchange_rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending_payment', 'payment_received', 'approved', 'rejected', 'cancelled', name='paymentstatus'), autoincrement=False, nullable=False),
    sa.Column('payment_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('banco_origen', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cédula_pagador', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('referencia_pago', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('comprobante_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('últimos_4_digitos', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reminder_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_reminder_at', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='upgrade_requests_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='upgrade_requests_pkey')
    )
    # ### end Alembic commands ###
